<?php

namespace DoctrineProxy\__CG__\Jowy\P2bj\Domain\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Jowy\P2bj\Domain\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'username', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'password', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'role', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'paket', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'log', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'createdAt', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'updatedAt');
        }

        return array('__isInitialized__', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'username', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'password', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'role', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'paket', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'log', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'createdAt', '' . "\0" . 'Jowy\\P2bj\\Domain\\Entity\\User' . "\0" . 'updatedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array());

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', array($role));

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function addPaket(\Jowy\P2bj\Domain\Entity\Paket $paket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPaket', array($paket));

        return parent::addPaket($paket);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaket', array());

        return parent::getPaket();
    }

    /**
     * {@inheritDoc}
     */
    public function timestampableCreateEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'timestampableCreateEvent', array());

        return parent::timestampableCreateEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function timestampableUpdateEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'timestampableUpdateEvent', array());

        return parent::timestampableUpdateEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getLog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLog', array());

        return parent::getLog();
    }

    /**
     * {@inheritDoc}
     */
    public function setLog($log)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLog', array($log));

        return parent::setLog($log);
    }

    /**
     * {@inheritDoc}
     */
    public function addLog(\Jowy\P2bj\Domain\Entity\Log $log)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLog', array($log));

        return parent::addLog($log);
    }

}
